TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += tektronixOsc.db
DATA += tektronixOsc.proto

#=======================================
include $(TOP)/configure/RULES
